### ISSUE TITLE
¿Cómo te hacemos llegar los desafíos?

### ISSUE THREAD

**Issue by eduardoprosales** [salvadoruriel/PCAdj#2]
Hola, quisiera saber si, cuando hagamos los desafíos en repl.it, ¿debemos compartirte un link por cada proyecto o en un mismo link todos? ¿Cómo se hace? ¿Por dónde lo publicamos? ¿Tendremos que generar un link diferente cada semana?

**Comment by salvadoruriel** [comment]
Como se mencionó al inicio, es un solo proyecto. Por lo que será el mismo enlace el que revisare.
Como si se lo mostraras a un cliente en otro país. Mas información en el foro de primer desafío en sea.
