### ISSUE TITLE
DESAFIOS

### ISSUE THREAD

**Issue by Chilangdon20** [salvadoruriel/PCAdj#3]
Adjunto las carpetas de los Desafios Yeyecoa así como de los desafios normales los cuales están hechos en python y en C.

DESAFIO YEYECOA PINO(Python):

Github:

https://github.com/Chilangdon20/Desafio_Yeyecoa_pinos

MEGA:

https://mega.nz/fm/mtMVSAQC

DESAFIO C (NO YEYECOA)

Github:

https://github.com/Chilangdon20/Desafio1

MEGA:

https://mega.nz/fm/rsNRBawR

**Comment by salvadoruriel** [comment]
Hola,
1. El enlace que compartes de mega es tu carpeta **privada**, debes compartir un enlace **público** si quieres que los demás lo vean. Prueba copiar y pegarlo en un navegador privado para ver si los enlaces que compartes lucen como deben.
2. Para una revisión y colaboración más lineal se revisaran los proyectos en repl.it, todos los que publicaron antes de la prórroga todavía se revisaran las carpetas individuales.
